- name: Create host independent directories which need to exist, if necessary
  file: path={{item}} state=directory owner=root
  with_items: 
    - "{{ mesos_master_config_dir }}"
  become: yes
  tags:
    - mesos-core
    - mesos-master
    - configuration

- name: Remove unused config files
  file: path={{item}} state=absent
  with_items: mesos_master_config_files_to_delete
  become: yes
  tags:
    - mesos-core
    - mesos-master
    - configuration

- name: Configure Mesos Master commandline flags
  template: src=mesos-master-flags/{{item}}.j2 dest={{mesos_master_config_dir}}/{{item}} owner=root group=root mode=0644
  with_items: mesos_master_args_files
  notify: restart mesos-master
  become: yes
  tags:
    - mesos-core
    - mesos-master
    - configuration

- name: Remove /etc/mesos/zk file
  file: path=/etc/mesos/zk state=absent
  become: yes
  tags:
    - mesos-core
    - mesos-master
    - configuration

- name: Disable mesos slave
  when: inventory_hostname not in groups.slaves
  service: name=mesos-slave state=stopped
  become: yes
  tags:
    - mesos-core
    - mesos-master
    - configuration

- name: Prevent mesos slave daemon from starting at system startup
  when: inventory_hostname not in groups.slaves
  template: src=mesos_slave_override.j2 dest=/etc/init/mesos-slave.override owner=root group=root mode=0644
  become: yes
  tags:
    - mesos-core
    - mesos-master
    - configuration
